# Generated by Django 4.0.3 on 2022-04-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFirma',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
                ('certificado', models.CharField(blank=True, max_length=600, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionFirma.usuario')),
            ],
            options={
                'verbose_name': 'formulario',
                'verbose_name_plural': 'formularios',
            },
        ),
        migrations.CreateModel(
            name='Borrador',
            fields=[
                ('id_borrador', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacionFirma.formulario')),
            ],
            options={
                'verbose_name': 'borrador',
                'verbose_name_plural': 'borradores',
            },
        ),
        migrations.CreateModel(
            name='ArchivoFirmado',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('borrador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacionFirma.borrador')),
                ('programafirma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacionFirma.programafirma')),
            ],
            options={
                'verbose_name': 'archivoFirmado',
            },
        ),
    ]
